apiVersion: v1
kind: Secret
metadata:
  name: disruptflow-secret
  namespace: disruptflow
type: Opaque
stringData:
  DB_URL: "jdbc:mysql://mysql-prod:3306/disrupt_flow?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=Asia/Shanghai"
  DB_USERNAME: "disruptflow"
  DB_PASSWORD: "replace-me"
  ROCKETMQ_NAMESRV_ADDR: "rocketmq-namesrv:9876"
  ROCKETMQ_PRODUCER_GROUP: "DisruptFlowProducerGroup"
  ROCKETMQ_CONSUMER_GROUP: "DisruptFlowConsumerGroup"
  RETRY_DISRUPTOR_TOPIC: "disruptorFlowException"
  RETRY_DISRUPTOR_TAGS: "disruptorFlowException"
