spring.profiles.active=dev

# 基础配置
spring.application.name=DisruptFlow

# RocketMQ 配置
rocketmq.enabled=true
rocketmq.name-server=127.0.0.1:9876
rocketmq.producer-group=DisruptFlowProducerGroup
rocketmq.consumer-group=DisruptFlowConsumerGroup
rocketmq.send-msg-timeout=3000
rocketmq.retry-times-when-send-failed=2
rocketmq.retry-times-when-send-async-failed=2
rocketmq.max-message-size=4194304
rocketmq.compress-msg-body-over-howmuch=4096
rocketmq.retry-another-broker-when-not-store-ok=false
rocketmq.producer.retry-disruptor-topic=disruptorFlowException
rocketmq.producer.retry-disruptor-tags=disruptorFlowException

# 线程池配置
async-push-disruptor-flow-executor.core-pool-size=10
async-push-disruptor-flow-executor.max-pool-size=16
async-push-disruptor-flow-executor.keep-alive-time=500
async-push-disruptor-flow-executor.queue-size=10

# 重试配置
retry.failed.count.limit=3

# 日志配置
logging.level.root=INFO
logging.level.com.chenxiaofei.disruptflow=DEBUG
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level [%X{traceId}] %logger{50} - %msg%n
logging.file.name=./logs/disrupt-flow.log