spring.application.name=disruptorFlow
asyncPushDisruptorFlowExecutor.corePoolSize=10
asyncPushDisruptorFlowExecutor.MaxPoolSize=16
asyncPushDisruptorFlowExecutor.keepAliveTime=500
asyncPushDisruptorFlowExecutor.queueSize=10

retry.failed.count.limit=3

rocketmq.producer.retryDisruptorTopic=disruptorFlowException
rocketmq.producer.retryDisruptorTags=disruptorFlowException