spring.application.name=disruptorFlow
asyncPushDisruptorFlowExecutor.corePoolSize=10
asyncPushDisruptorFlowExecutor.MaxPoolSize=16
asyncPushDisruptorFlowExecutor.keepAliveTime=500
asyncPushDisruptorFlowExecutor.queueSize=10

